n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))
print("The numbers are ", n1, "and", n2)
print("num1 & num2 = ", n1 & n2)
print("num1 | num2 = ", n1 | n2)
print("num1 ^ num2 = ", n1 ^ n2)
print("num1 << num2 = ", n1 << n2)
print("num1 >> num2 = ", n1 >> n2)
print("num1 ~ = ", ~n1)
print("num2 ~ = ", ~n2)