print("These are my most favourite people:")
person1_name = input("Enter the name of your first favourite person: ")
dob_person1 = input("Enter the date of birth of your first favourite person: ")
person2_name = input("Enter the name of your second favourite person: ")
dob_person2 = input("Enter the date of birth of your second favourite person: ")
person3_name = input("Enter the name of your third favourite person: ")
dob_person3 = input("Enter the date of birth of your third favourite person: ")
person4_name = input("Enter the name of your fourth favourite person: ")
dob_person4 = input("Enter the date of birth of your fourth favourite person: ")
person5_name = input("Enter the name of your fifth favourite person: ")
dob_person5 = input("Enter the date of birth of your fifth favourite person: ")
person6_name = input("Enter the name of your sixth favourite person: ")
dob_person6 = input("Enter the date of birth of your sixth favourite person: ")
person7_name = input("Enter the name of your seventh favourite person: ")
dob_person7 = input("Enter the date of birth of your seventh favourite person: ")
person8_name = input("Enter the name of your eighth favourite person: ")
dob_person8 = input("Enter the date of birth of your eighth favourite person: ")
person9_name = input("Enter the name of your ninth favourite person: ")
dob_person9 = input("Enter the date of birth of your ninth favourite person: ")
person10_name = input("Enter the name of your tenth favourite person: ")
dob_person10 = input("Enter the date of birth of your tenth favourite person: ")
print("My first favourite person is ", person1_name, " and was born on ", dob_person1)
print("My second favourite person is ", person2_name, " and was born on ", dob_person2)
print("My third favourite person is ", person3_name, " and was born on ", dob_person3)
print("My fourth favourite person is ", person4_name, " and was born on ", dob_person4)
print("My fifth favourite person is ", person5_name, " and was born on ", dob_person5)
print("My sixth favourite person is ", person6_name, " and was born on ", dob_person6)
print("My seventh favourite person is ", person7_name, " and was born on ", dob_person7)
print("My eighth favourite person is ", person8_name, " and was born on ", dob_person8)
print("My ninth favourite person is ", person9_name, " and was born on ", dob_person9)
print("My tenth favourite person is ", person10_name, " and was born on ", dob_person10)