print("Welcome to our programme")
name = input("Enter your name: ")
print("Assalamu Alaikum, ", name, "! Nice to meet you.")
condition = bool(input("Are you fine? Please answer in 'True' or 'False': "))
print("You are fine. This statement is ", condition)
print(type(name))
print(type(condition))