print("Assalamu Alaikum World!")
name = input("Enter your name: ")
birth_year = int(input("Enter your year of birth: "))
number = input("Enter your favourite number: ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")
address = input("Enter the address of where you live in: ")
age = int(2024 - birth_year)
print("My name is ", name, " and I am ", age, " years old. My favourite number is ", number)
print("My email address is: ", email)
print("My phone number: ", phone)
print("I live in ", address)