print("Welcome to square-root calculator! Any number, including integers and floating point numbers can be calculated here.")
number = float(input("Enter any number to calculate square root : "))
sq_root = number**(1/2)
print("The required square root of your number is : ", sq_root)
print("If you want to calculate the area of an equilateral triangle, diagonal of a square, you must use some values.")
sq_root_2 = 2**(1/2)
sq_root_3 = 3**(1/2)
sq_root_5 = 5**(1/2)
print("The square root of 2 is useful for determining the diagonal of a square. Its value is about ", sq_root_2)
print("The square root of 3 is useful for factors concerning equilateral triangles. Its value is about ", sq_root_3)
print("The square root of 5 is used for determining the golden ratio. The square root of 5 is about ", sq_root_5)
print("The golden ratio is represented by phi, and its value is about ", ((1 + sq_root_5)/2))